### PR TITLE
Fix string-template for dot-expression from which the  toString() is removed

### LINKED ISSUE #996: Internal error no-unused-imports
## Observed Behavior
Running ktlint with parameter "-F" produces an internal error "no-unused-imports" on enclosed sample code. Running *without* parameter "-F" actually produces a helpful message.

## Steps to Reproduce
Run "ktlint -F" on code below:
```
package com.example.ktlint.error

import mu.KLogging

class NoUnsedImportInternalErrorKtlint {

    fun getDrafts(val draftsIds: List<Long>) {
        logger.info { "Entering getDrafts: draftIds=[${draftsIds.toString()}]" }
    }

    private companion object : KLogging() {
    }
}
```

results in:
`
NoUnsedImportInternalErrorKtlint.kt:1:1: Internal Error (no-unused-imports). Please create a ticket at https://github.com/pinterest/ktlint/issues (if possible, provide the source code that triggered an error) (cannot be auto-corrected)
`

without parameter "-F", the result is:
`
NoUnsedImportInternalErrorKtlint.kt:8:65: Redundant "toString()" call in string template
`

After removing the redundant "toString" the problem is gone.

## Your Environment
Ktlint version 0.39.0
MacOs

### PR DESCRIPTION
**Pull request by paul-dingemans**
Given code example below:
```
                fun getDrafts(val draftsIds: List<Long>) {
                    println("draftIds=[${'$'}{draftsIds.toString()}]")
                }
```
Formatting with autocorrect of this code fails on the no-unused-imports rule as the dot-expression node still exists but the toString invocation was already removed.

Resolves #996

### CODE REVIEW

**Comment by paul-dingemans** [comment]
This might fix #1019 although this is not sure as the issue could not be reproduced.

File: ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StringTemplateRule.kt [hunk 1]
```diff
@@ -65,9 +69,19 @@ class StringTemplateRule : Rule("string-template") {
             ) {
                 emit(node.treePrev.startOffset + 2, "Redundant curly braces", true)
                 if (autoCorrect) {
-                    // fixme: a proper way would be to downcast to SHORT_STRING_TEMPLATE_ENTRY
-                    (node.firstChildNode as LeafPsiElement).rawReplaceWithText("$") // entry start
-                    (node.lastChildNode as LeafPsiElement).rawReplaceWithText("") // entry end
+                    val leftCurlyBraceNode = node.findChildByType(LONG_TEMPLATE_ENTRY_START)
+                    val rightCurlyBraceNode = node.findChildByType(LONG_TEMPLATE_ENTRY_END)
+                    if (node.children().count() == 3 && leftCurlyBraceNode != null && rightCurlyBraceNode != null) {
```
Comment (romtsn) [inline ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StringTemplateRule.kt:74]: Could you elaborate on why `count` is 3 exactly? I guess I am missing a bit of context :)

Comment (paul-dingemans) [reply ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StringTemplateRule.kt:74]: It is a bit of defensive programma. The block above is surrounded by the following if-statement:
```
            if (node.text.startsWith("${'$'}{") &&
                node.text.let { it.substring(2, it.length - 1) }.all { it.isPartOfIdentifier() } &&
                (entryExpression is KtNameReferenceExpression || entryExpression is KtThisExpression) &&
                node.treeNext.let { nextSibling ->
                    nextSibling.elementType == CLOSING_QUOTE ||
                        (
                            nextSibling.elementType == LITERAL_STRING_TEMPLATE_ENTRY &&
                                !nextSibling.text[0].isPartOfIdentifier()
                            )
                }
            ) {
```
I was not 100% sure that this statement really covers the situation of a prefix-node, content-node and a suffix-node. In case that also prefix-node, content-node-1, ...,  content-node-n, suffix-node can match this statement then I do think it is not a valid to prefix only the first node with the '$'. So line 74 guards the autocorrect to patterns which can be corrected safely.
