### PR TITLE
ArgumentListWrappingRule: don't report it when line breaks is inside a lambda

### LINKED ISSUE #861: False Positive for ParameterListWrapping
Follow up from https://github.com/pinterest/ktlint/pull/786#issuecomment-680874240

## Expected Behavior
ParameterListWrapping is not raised.

## Observed Behavior
ParameterListWrapping is raised after upgrading to Detekt 1.12.0, but not before.

Fails with `Argument should be on a separate line (unless all arguments can fit a single line)` and `Missing newline before ")"` .

## Steps to Reproduce
```kotlin
foo(bar.apply {
    // stuff
})
```

## Your Environment

* Version of ktlint used: 0.38.1 (according to [detekt changelog](https://detekt.github.io/detekt/changelog.html))
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): `./gradlew detekt`
* Version of Gradle used (if applicable): 6.6.1
* Operating System and version: OSX 10.15.6

### LINKED ISSUE #870: Parameter wrapping autocorrect unindents lines after first in lambda block
## Expected Behavior

```kotlin
package test

private fun main() {
    println(
        Runnable {
            println("hello")
            println("world")
        }
    )
}
```

## Observed Behavior

```kotlin
package test

private fun main() {
    println(
        Runnable {
            println("hello")
    println("world")
        }
    )
}
```

## Steps to Reproduce

```editorconfig
[*.{kt,kts}]
disabled_rules=indent
```
```kotlin
package test

private fun main() {
    println(Runnable {
        println("hello")
        println("world")
    })
}
```

## Your Environment

* Version of ktlint used: 0.38.1
* Name and version: `ktlint --format`
* Version of Gradle used (if applicable):
* Operating System and version:
* Link to your project (if it's a public repository):

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #861
Fixes #870

### CODE REVIEW

File: ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRuleTest.kt [hunk 1]
```diff
@@ -254,9 +285,9 @@ class ArgumentListWrappingRuleTest {
     }
 
     @Test
-    fun testFormatPreservesIndentWithAnnotationsOnMultiLine() {
+    fun testLintPreservesIndentWithAnnotationsOnMultiLine() {
```
Comment (romtsn) [inline ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRuleTest.kt:288]: hm, why this has been changed?

Comment (t-kameyama) [reply ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRuleTest.kt]: Undid the test.

**Comment by romtsn** [comment]
Perfect, thank you!
