### PR TITLE
Fix formatting with comments (`colon-spacing`)

### LINKED ISSUE #1057: multiline expressions transformed to single line inside comment
## Expected Behavior

```
var x // check it out
: String = "hi"
```
should be transformed to
```
var x: String = "hi" // check it out
```

## Observed Behavior

```
var x // check it out
: String = "hi"
```
outputs to
```
var x // check it out: String = "hi"
```

## Your Environment

* Version of ktlint used: 0.40.0
* Name and version: custom gradle task and command line

### PR DESCRIPTION
**Pull request by t-kameyama**
## Description
Fixes #1057

## Checklist

- [x] tests are added
- [x] `CHANGELOG.md` is updated

### CODE REVIEW

File: ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundColonRuleTest.kt [hunk 1]
```diff
@@ -248,15 +248,49 @@ class SpacingAroundColonRuleTest {
...
+            SpacingAroundColonRule().format(
+                """
+                val x // comment
+                    : Int = 1
+                """.trimIndent()
+            )
+        ).isEqualTo(
+            """
+                val x: // comment
+                    Int = 1
```
Comment (Tapchicoma) [inline ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundColonRuleTest.kt:292]: Not sure it is the best way to format :thinking: 
Property type should be, imho, on the same line with property name. Probably formatted code could look like this:
```kotlin
val x: Int = // comment
    1
```

or like this:
```kotlin
// comment
val x: Int = 1
```

What do you think?

Comment (t-kameyama) [reply ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundColonRuleTest.kt]: > ```kotlin
> val x: Int = // comment
>     1
> ```
I think this is better.
Fixed in 9460b58.

**Review by Tapchicoma — APPROVED** [review]
LGTM!
