### PR TITLE
Fix traversing the directory hierarchy on WindowsOS / Ant-style path matching

### LINKED ISSUE #1600: Traversing the directory hierarchy is broken on Windows as of version 0.47
## Expected Behavior

Running `ktlint` w/o specifying any input files previously made it search for `*.kt` and `*.kts` files, starting from the current directory, e.&nbsp;g.:

```console
$ ./ktlint
14:54:01.402 [main] INFO com.pinterest.ktlint.internal.KtlintCommandLine - Enable default patterns [**/*.kt, **/*.kts]
10:56:53.905 [main] DEBUG com.pinterest.ktlint.internal.KtlintCommandLine - 6821ms / 14 file(s) / 167 error(s)
```

This behaviour still holds when `ktlint` is run from the command line on _Linux_ or _Mac OS X_.

## Observed Behavior

Yet, using just the very same command line switches on _Windows_ (i.&nbsp;e. when running `ktlint` from _Git Bash_) results in no input files being found:

```console
15:01:09.889 [main] INFO com.pinterest.ktlint.internal.KtlintCommandLine - Enable default patterns [**\\*.kt, **\\*.kts]
15:01:10.457 [main] ERROR com.pinterest.ktlint.internal.KtlintCommandLine - No files matched [**\\*.kt, **\\*.kts]
```

This is a clear regression against version **0.46.1** and, apparently, has been caused by the [recent changes](https://github.com/pinterest/ktlint/pull/1533) which re-enable (sort of &mdash; see #1601) the parsing of [_Ant_-like path patterns](https://www.jetbrains.com/help/teamcity/wildcards.html#Antlike+Wildcards) (e.g.: `**/*.kt`) &mdash; which was broken in version **0.46.1**.

## Steps to Reproduce

1. Download the fat JAR from https://github.com/pinterest/ktlint/releases/tag/0.47.0.
2. Run the far JAR against any non-empty codebase on Windows:
    ```bash
    java -Xmx512m --add-opens java.base/java.lang=ALL-UNNAMED -jar ktlint
    ```
## Your Environment

* Version of ktlint used: **0.47**
* Relevant parts of the `.editorconfig` settings: none
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): **CLI**
* Version of Gradle used (if applicable): N/A
* Operating System and version:
   * `MINGW64_NT-10.0-19043 unit-725 3.3.4-341.x86_64 2022-05-09 11:56 UTC x86_64 Msys`
   * `Linux unit-725 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux`

### LINKED ISSUE #1601: Ant-style path pattern support broken when `ktlint` is invoked from the command line
## Expected Behavior

Judging from its documentation, `ktlint` should support _Ant_-style path patterns, as described in

 * https://ant.apache.org/manual/dirtasks.html#patterns
 * https://www.jetbrains.com/help/teamcity/wildcards.html#Antlike+Wildcards
 * https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html

## Observed Behavior

Consider I have one or more `*.kt` files in the `src/` subdirectory of the current directory.

 * The invocation below works, the regular shell wildcard gets expanded by any POSIX-compliant shell:
    ```bash
    ktlint src/*.kt
    ```
 * Any of these invocations work in `zsh` (the more complex _Ant_-style patterns get expanded by the shell itself):
   ```zsh
   ktlint **/*.kt
   ktlint ./**/*.kt
   ktlint src/**/*.kt
   ktlint ./src/**/*.kt
   ktlint **/src/*.kt
   ktlint ./**/src/*.kt
   ktlint **/src/**/*.kt
   ktlint ./**/src/**/*.kt
   ```

Now, let's enclose the last argument in double quotes so that it gets expanded (as we hope for) by `ktlint` rather than the underlying shell:

 * `ktlint "src/*.kt"` &mdash; doesn't work (`No files matched [src/*.kt]`).
 * `ktlint "**/*.kt"` &mdash; works.
 * `ktlint "./**/*.kt"` &mdash; doesn't work.
 * `ktlint "src/**/*.kt"` &mdash; doesn't work (this is actually the example from the output of  `ktlint --help`).
 * `ktlint "./src/**/*.kt"` &mdash; doesn't work.
 * `ktlint "**/src/*.kt"` &mdash; doesn't work.
 * `ktlint "./**/src/*.kt"` &mdash; doesn't work.
 * `ktlint "**/src/**/*.kt"` &mdash; doesn't work.
 * `ktlint "./**/src/**/*.kt"` &mdash; doesn't work.

## Steps to Reproduce

 * Download the fat JAR from https://github.com/pinterest/ktlint/releases/tag/0.47.0.
 * Run the far JAR against any non-empty codebase, using either a POSIX shell or `cmd.exe`:
    ```bash
    java -Xmx512m --add-opens java.base/java.lang=ALL-UNNAMED -jar ktlint <path pattern(s)>
    ```

## Your Environment

* Version of ktlint used: **0.47**.
* Relevant parts of the `.editorconfig` settings: none
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): **CLI**
* Version of Gradle used (if applicable): N/A
* Operating System and version:
  * `MINGW64_NT-10.0-19043 unit-725 3.3.4-341.x86_64 2022-05-09 11:56 UTC x86_64 Msys`
  * `Linux unit-725 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux`

### PR DESCRIPTION
**Pull request by paul-dingemans**
## Description

Globs always use a "/" as directory separator on all OS's. Input patterns containing a "\" on Windows OS are transformed to "/" as users on Windows more likely would assume that the "\" may be used.

On WindowsOS, transform "\" in the filepath to "/" before comparing the filename with the regular expression (of the glob) which always uses "/" as separator.

Refactor all logic which create globs based on an input path.
- If a path (absolute or relative) point to a directory, that path is expanded to the default globs (*.kt, *.kts) in that specific directory or any of its subdirectories.
- If a path (absolute or relative) does not point to a directory, e.g. it
  points to a file, or it is a pattern. See "**" replacement below.
- On Windows OS patters containing a "*" (or "**") can not be resolved with default Paths utilities. In such case the given input pattern is handled as is. See "**" replacement below.

Patterns that contain one or more occurrence of a "**" are split into multiple patterns so that files on that specific path and subdirectories will be matched.
- For example, for path "some/path/**/*.kt" an additional pattern "some/path/*.kt" is generated to make sure that not only the "*.kt" files in a subdirectory of "some/path/" are found but also the "*.kt" in directory "some/path" as well. This is in sync with the "**" notation in a glob which should be interpreted as having zero or more intermediate subdirectories.
- For example, for path "some/**/path/**/*.kt", multiple additional patterns are generated. As it contains two "**" patterns, 2 x 2 patterns are needed to match all possible combinations:
   - "some/**/path/**/*.kt"
   - "some/**/path/*.kt"
   - "some/path/**/*.kt"
   - "some/path/*.kt"

Finally, on Windows OS more fixes are needed as the resulting globs may not contain any drive destinations as the start of the path. Such a drive destination is replaced with a "**". So "D:/some/path/*.kt" becomes "/some/path/*.kt". Note that the last glob representation is less strict than the original pattern as it could match on other drives that "D:/" as well.

Extend trace logging.

Closes #1600
Closes #1601
## Checklist

- [X] PR description added
- [X] tests are added
- [X] KtLint has been applied on source code itself and violations are fixed
- [ ] [documentation](https://pinterest.github.io/ktlint/) is updated
- [X] `CHANGELOG.md` is updated

In case of adding a new rule:
- [ ] Rule is added to [rules documentation](https://pinterest.github.io/ktlint/rules/standard/)

### CODE REVIEW

File: ktlint/src/main/kotlin/com/pinterest/ktlint/internal/FileUtils.kt [hunk 1]
```diff
@@ -198,13 +204,19 @@ internal fun JarFiles.toFilesURIList() = map {
...
         this
     } else {
         replaceFirst(tildeRegex, userHome)
     }
 
+private val onWindowsOS
+    get() =
+        System
+            .getProperty("os.name")
+            .startsWith("windows", true)
```
Comment (Goooler) [inline ktlint/src/main/kotlin/com/pinterest/ktlint/internal/FileUtils.kt:218]:
```suggestion
private val onWindowsOS: Boolean
    get() = System.getProperty("os.name").startsWith("windows", true)
```
