### PR TITLE
Fix KDOC indentation for tab indentation style

### LINKED ISSUE #850: Tab indentation breaks KDoc comments
## Expected Behavior
```kotlin
/**
 * some function
 */
fun someFunction() {
	return Unit
}
```

## Observed Behavior
```kotlin
/**
	* some function
	*/
fun someFunction() {
	return Unit
}
```

## Steps to Reproduce
`ktlint -F whatever.kt`

I'm fairly certain that [this](https://github.com/pinterest/ktlint/blob/56e0ce2849fce6abc63727f864f4b08eb4899816/ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt#L1055) is the reason for this behavior, i.e. it adds one of whatever indentation (space or tab) instead of one space. I think it's probably best to [ignore both `BLOCK_COMMENT` and `KDOC`](https://github.com/pinterest/ktlint/blob/56e0ce2849fce6abc63727f864f4b08eb4899816/ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt#L968). There also doesn't seem to be a test for that; I think adding a KDoc comment to [this test](https://github.com/pinterest/ktlint/blob/56e0ce2849fce6abc63727f864f4b08eb4899816/ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt#L29) should suffice.

I already tried fixing it but didn't really get anywhere; I might open a PR in a few days if I manage to fix it.

## Your Environment

* Version of ktlint used: 0.38.0
* `.editorconfig` contains `indent_style = tab`

### PR DESCRIPTION
**Pull request by paul-dingemans**
Fix #850 

## Description

The space before the continuation and end of a KDoc line is now preserved in case the tab indentation style is used.

Fixes https://github.com/pinterest/ktlint/issues/850

## Checklist

- [X] tests are added
- [x] `CHANGELOG.md` is updated

### CODE REVIEW

File: ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt [hunk 1]
```diff
@@ -673,16 +674,6 @@ class IndentationRule : Rule("indent"), Rule.Modifier.RestrictToRootLast {
         if (!ctx.ignored.contains(p) && nextSibling != null) {
             expectedIndent++
             debug { "++inside(${p.elementType}) -> $expectedIndent" }
-            val siblingType = nextSibling.elementType
```
Comment (romtsn) [inline ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt:676]: This is just a cleanup, right?

**Review by romtsn — APPROVED** [review]
LGTM, please, add a changelog entry.
Also, in the future, please mention the issue number in the PR description, so it can be linked and closed accordingly.

File: ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt (hunk 1 above)
Comment (paul-dingemans) [reply ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt:676]: Yes, that is right. I committed this separately with message `remove unused variables`.

**Comment by paul-dingemans** [comment]
> LGTM, please, add a changelog entry. Also, in the future, please mention the issue number in the PR description, so it can be linked and closed accordingly.

Will add the changelog. I mentioned the issue number in the commit message and thought that was enough. I will mentioned it in the PR description next time as well.
