### PR TITLE
fix SpacingAroundCommaRule when comma goes after comment

### LINKED ISSUE #367: Comma on newline preceded by // comment will move code into comment
I got a when phrase. The case is

before
```java
when (type) {
            IHomeLivingConstant.LIVING_TYPE_GUESS_YOU_LIKE //a
                , IHomeLivingConstant.Live_MODULE_CONTENT_CODE // b
                , IHomeLivingConstant.LIVE_MODULE_AUTO_PLAY  //c
-> {
    // do something
}
```

after formatting, I turn out
```java
when (type) {
            IHomeLivingConstant.LIVING_TYPE_GUESS_YOU_LIKE //a, IHomeLivingConstant.Live_MODULE_CONTENT_CODE // b, IHomeLivingConstant.LIVE_MODULE_AUTO_PLAY  //c
-> {
    //do something
} 

```

This lead to bugs cause it will not invoke compile error, but is wrong logically.  And it is hard to find the bug in the hundreds of formatted files.

### PR DESCRIPTION
**Pull request by z3d1k**
Disable autocorrection for comma spacing rule if comma on newline preceded by // comment.

Fixes #367

### CODE REVIEW

File: ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundCommaRule.kt [hunk 1]
```diff
@@ -19,9 +20,10 @@ class SpacingAroundCommaRule : Rule("comma-spacing") {
         if (node is LeafPsiElement && node.textMatches(",") && !node.isPartOfString()) {
             val prevLeaf = node.prevLeaf()
             if (prevLeaf is PsiWhiteSpace) {
-                emit(prevLeaf.startOffset, "Unexpected spacing before \"${node.text}\"", true)
-                if (autoCorrect) {
-                    prevLeaf.node.treeParent.removeChild(prevLeaf.node)
+                val canBeAutoCorrected = prevLeaf.prevLeaf { it !is PsiWhiteSpace } !is PsiComment
+                emit(prevLeaf.startOffset, "Unexpected spacing before \"${node.text}\"", canBeAutoCorrected)
```
Comment (shashachu) [inline ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundCommaRule.kt]: Since this is a weird edge case, might be nice to add some more info about why it can't be auto corrected.

Comment (z3d1k) [reply ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundCommaRule.kt]: I added a comment with link to a related issue, is that enough?

Comment (shashachu) [reply ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundCommaRule.kt]: @z3d1k in-code comments are great but I actually meant the text output by ktlint. Most people will probably be using ktlint as a tool and not looking at the code, and since *most* of the time, this rule can be auto-corrected, it might look like a bug that it doesn't autocorrect in this case. Thoughts?

Comment (JLLeitschuh) [reply ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundCommaRule.kt]: > in-code comments are great but I actually meant the text output by ktlint.
I agree with this sentiment.

**Comment by z3d1k** [comment]
@shashachu I managed to make auto correction work, but ran into another comment related case.
This code 
`fun main() { x(1 /* comment */ , 3); x(1 /* comment */, 3) }`
 will be formatted by current version as follows
`fun main() { x(1 /* comment */, 3); x(1 /* comment */, 3) }`
After this fix it became
`fun main() { x(1, /* comment */ 3); x(1 /* comment */, 3) }`
Is this behavior correct, or it should be left as it is now?

Also, maybe you can come up with other scenarios where auto correction might not work as expected in this rule?

**Comment by shashachu** [comment]
> @shashachu I managed to make auto correction work, but ran into another comment related case.
> This code
> `fun main() { x(1 /* comment */ , 3); x(1 /* comment */, 3) }`
> will be formatted by current version as follows
> `fun main() { x(1 /* comment */, 3); x(1 /* comment */, 3) }`
> After this fix it became
> `fun main() { x(1, /* comment */ 3); x(1 /* comment */, 3) }`
> Is this behavior correct, or it should be left as it is now?

Sorry for the late reply. That doesn't look correct, as the intended behavior is to attach the comment to the first parameter, not the second.

**Comment by z3d1k** [comment]
I agree. My last commit fixed it, now the comma is only moved before the comment in case if comma is on a new line. Check out the tests.

**Comment by shashachu** [comment]
Sorry for the delay - looks good to me. Thanks!
