### PR TITLE
ParameterListWrappingRule: correctly indent primary constructor parameters when class has multiline type parameter

### LINKED ISSUE #921: Conflicting constructor argument indentation requirements for class with linewrapping type list
We have some code that looks like this:

```
class ComposableLambda<
    P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16,
    P17, P18, R>(
    val key: Int,
    private val tracked: Boolean,
    private val sourceInformation: String?
)
```

We we run `./gradlew ktlint` with ktlint version 0.39.0, it fails, saying that we need to indent these last four lines by 4 characters each:

```
ComposableLambda.kt:50:5: Unexpected indentation (expected 8, actual 4)
ComposableLambda.kt:51:5: Unexpected indentation (expected 8, actual 4)
ComposableLambda.kt:52:5: Unexpected indentation (expected 8, actual 4)
ComposableLambda.kt:53:1: Unexpected indentation (expected 4, actual 0)
```

Then we make those changes:

```
class ComposableLambda<
    P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16,
    P17, P18, R>(
        val key: Int,
        private val tracked: Boolean,
        private val sourceInformation: String?
    )
```

it fails again, asking us to undo those changes:

```
ComposableLambda.kt:50:1: Unexpected indentation (8) (should be 4)
ComposableLambda.kt:51:1: Unexpected indentation (8) (should be 4)
ComposableLambda.kt:52:1: Unexpected indentation (8) (should be 4)
ComposableLambda.kt:53:1: Unexpected indentation (4) (should be 0)
```

## Expected Behavior
Whichever indendation ktlint expects, it should accept the indentation that it asks for

## Observed Behavior
We haven't been able to find an indentation that ktlint will accept

## Your Environment
We're observing this when upgrading from ktlint 0.36.0 to 0.39.0

The complete code in question:

https://android.googlesource.com/platform/frameworks/support/+/7f584eb57aae1bf6513e390117ecd66f16dde2a7/compose/runtime/runtime/src/commonMain/kotlin/androidx/compose/runtime/internal/ComposableLambda.kt#47

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #921

### CODE REVIEW

File: ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/ParameterListWrappingRuleTest.kt [hunk 1]
```diff
@@ -563,4 +563,24 @@ class ParameterListWrappingRuleTest {
...
+            ParameterListWrappingRule().lint(
+                """
+                class ComposableLambda<
+                    P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16,
+                    P17, P18, R>(
+                    val key: Int,
+                    private val tracked: Boolean,
+                    private val sourceInformation: String?
+                )
+                // https://github.com/pinterest/ktlint/issues/938
```
Comment (romtsn) [inline ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/ParameterListWrappingRuleTest.kt:580]: What's this comment about? does this also fix #938?

Comment (t-kameyama) [reply ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/ParameterListWrappingRuleTest.kt]: It's just a mistake.

**Review by romtsn — APPROVED** [review]

**Comment by romtsn** [comment]
Thanks
