### PR TITLE
Fix indentation of secondary constructor

### LINKED ISSUE #1222: Code indents are according to Super call instead of to the main constructor block
## Expected Behavior
This is how Android Studio formats the code:
```
    constructor(context: Context, attrs: AttributeSet?, defStyleAttr: Int) : super(context, attrs, defStyleAttr) {
        init(attrs, defStyleAttr)
    }

    constructor(context: Context, attrs: AttributeSet?, defStyleAttr: Int, defStyleRes: Int) :
        super(context, attrs, defStyleAttr, defStyleRes) {
        init(attrs, defStyleAttr, defStyleRes)
    }
```
Notice how beautiful and logical the two constructors look, aligned and indented the same way.

## Observed Behavior
This is how I have to format my code in order to satisfy ktlint:
```
    constructor(context: Context, attrs: AttributeSet?, defStyleAttr: Int) : super(context, attrs, defStyleAttr) {
        init(attrs, defStyleAttr)
    }

    // @formatter:off
    constructor(context: Context, attrs: AttributeSet?, defStyleAttr: Int, defStyleRes: Int) :
        super(context, attrs, defStyleAttr, defStyleRes) {
            init(attrs, defStyleAttr, defStyleRes)
        }
    // @formatter:on
```
Notice how the second constructor is indented in a weird way, the code is aligned to the "super" call instead of to the actual function. (and I have to use "@formatter:off - on" to prevent the IDE formatter from making it right and breaking ktlint)

## Steps to Reproduce
I've imported the config from ktlint via `ktlint --android applyToIDEAProject` (on top of the Default Android studio config).

This is reproducible in all these cases:
- WIth and without my (small) customizations of the config
- With and without an `.editorconfig`

## Your Environment
ktlint:0.42.1
Android Studio Arctic Fox | 2020.3.1 Patch 1 (Build #AI-203.7717.56.2031.7621141, built on August 7, 2021)
macOS 11.5.2

Same problem when I run it via gradle or command line. (the gradle task is the same as in the ktlint readme)

### PR DESCRIPTION
**Pull request by paul-dingemans**
## Description

Fix indentation of secondary constructor

The call to `super` needs an additional indent compared to other situation in which a colon is found. Resulting code now looks like:
```
class Issue1222 {
    constructor(string1: String, string2: String2) :
            super(
                string1, string2
            ) {
        // do something
    }
}
```

Closes #1222

## Checklist

- [X] tests are added
- [X] `CHANGELOG.md` is updated

### CODE REVIEW

File: ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt [hunk 1]
```diff
@@ -765,13 +766,24 @@ class IndentationRule : Rule("indent"), Rule.Modifier.RestrictToRootLast {
...
-            ctx.exitAdjBy(n.treeParent, -1)
+        when {
+            n.isPartOf(FUN) -> {
+                expectedIndent++
+                debug { "++after(COLON IN FUN) -> $expectedIndent" }
+                val returnType = n.nextCodeSibling()
+                ctx.exitAdjBy(returnType!!, -1)
+            }
+            n.treeParent.isPartOf(SECONDARY_CONSTRUCTOR) -> {
+                expectedIndent += 2
```
Comment (romtsn) [inline ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt:777]:
```suggestion
                expectedIndent++
```
We don't support continuation indent at the moment.

The reason you've got this code indented as you mentioned in the original issue is that you're using `ij_kotlin_continuation_indent_in_supertype_lists` probably.

File: ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt [hunk 2]
```diff
@@ -765,13 +766,24 @@ class IndentationRule : Rule("indent"), Rule.Modifier.RestrictToRootLast {
...
+                debug { "++after(COLON IN CONSTRUCTOR) -> $expectedIndent" }
+                val returnType = n.nextCodeSibling()
+                ctx.exitAdjBy(returnType!!, -2)
```
Comment (romtsn) [inline ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt:780]:
```suggestion
                ctx.exitAdjBy(returnType!!, -1)
```

**Review by romtsn — CHANGES_REQUESTED** [review]

**Review by romtsn — APPROVED** [review]
