### PR TITLE
IndentationRule: Fix incorrect indentation for multi-line call expressions in conditions

### LINKED ISSUE #959: Incorrect indentation with multi-line conditions
Seems there's an issue with formatter (version 0.39.0).

In this artificial code example IDEA (Android Studio) formats it as:
```
fun test() {
    val result = true &&
        minOf(
            1, 2
        ) == 2 // this line
}
```
which looks correct.

But ktlint formats it as
```
fun test() {
    val result = true &&
        minOf(
            1, 2
    ) == 2 // this line
}
```
(notice, the `) == 2` line is aligned with the whole `val` and not its method `minOf`.

The key difference is comparison `== 2`, which breaks the formatting, because ktlint formats it correctly for a similar case with no final comparison:
```
fun test() {
    val result = true &&
        checkNotNull(
            true,
            { "test" }
        ) // this line
}
```

### PR DESCRIPTION
**Pull request by romtsn**
Close #959

### CODE REVIEW

**Comment by Tapchicoma** [comment]
@romtsn there is style violation :slightly_smiling_face: 
```
/home/travis/build/pinterest/ktlint/ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt:784:1: Needless blank line(s)
```

File: ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt [hunk 1]
```diff
@@ -762,4 +762,22 @@ internal class IndentationRuleTest {
...
+                        minOf(
+                            1, 2
+                        ) == 2
+                }
+                """.trimIndent()
+            )
+        ).isEmpty()
+    }
 }
+
```
Comment (romtsn) [inline ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt:783]:
```suggestion
```
